Added two (pretty large) features. See description.
James-Hackett/AwF-Bot pull request #1
Opened 2020-08-27 15:14 UTC by oof2win2

When deployed, the game chat things such as [gps=..], [armor=..] will no longer appear in the Discord chat! They are removed using regex searches. Also, hopefully correctly, added a feature that should theoretically write the name of the user or channel mentioned on Discord into the Factorio chat rather than the channel or user IDs, making it more readable by humans.

2020-08-27 23:39 UTC, James-Hackett requested changes
Review comments, should be okay then!

2020-08-27 23:39 UTC, James-Hackett commented on index.js
> +      message.content = message.content.replace(/<@[\S.]*>/, '@'+user);
Not sure this will work, try doing user.username instead

2020-08-27 23:39 UTC, James-Hackett commented on index.js
> +      message.content = message.content.replace(/<#[\S.]*>/, '#'+channel);
Also not sure if this will work, may need to do channel.name

2020-08-28 05:38 UTC, oof2win2 commented
Both would work as-is, as they request the channels and users mentioned, not the user or channel it was sent by/in.

2020-08-28 11:34 UTC, merged